### ISSUE TITLE
Improve/Add cairo tests

### ISSUE THREAD

**Issue by gianalarcon** [The-Marquis-Gaming/themarquis-ui#33]
## Issue Overview

1. Improve current [test](https://github.com/The-Marquis-Gaming/themarquis-ui-sc/tree/main/packages/snfoundry/contracts/src/test) of smart contracts
2.  If you execute all tests, the rpc api will reach a limit and it will stop without executing all the tests. WE have to use some external provider rpc api like alchemy or infura to solve this issue. 

### How to reproduce: 
1. git checkout `test-develop` branch
2. input command: `yarn test` (make sure you did `yarn install` before)
![image](https://github.com/user-attachments/assets/d83dfba7-c972-45c7-b954-b2e0fd2666b4)

## Proposed Solutions or Ideas

0. You have to work in branch `test-develop`
1.  Add loops and reuse tests in order to avoid to execute too much computation. Can refactor tests
2.  Improve the current .toml or the .env in order to execute tests using private rpc api without exposing it publicly 
![image](https://github.com/user-attachments/assets/7c854ee5-864b-4073-9f78-271f09d1fd62)

**Comment by nonso7** [comment]
Can I tackle this one?

**Comment by SoarinSkySagar** [comment]
May I work on this one @gianalarcon?

approach: I have used snforge tons of times in the past and I am very experienced in writing cairo tests. I will update/add new cairo tests for all the current functions, and make sure everything passes

eta: 3/4 days

**Comment by petersdt** [comment]
May I try my hand at this?

**Comment by jaiminRaiyani** [comment]
Would love to tackle this!

**Comment by caxtonacollins** [comment]
May I be assigned to this?

**Comment by BrunoAmbricca** [comment]
I would like to work on this issue

**Comment by ShantelPeters** [comment]
Can I try solving this issue?

**Comment by Jake1698** [comment]
can I try this one pls?

**Comment by Amarjeet325** [comment]
Can I take this issue?

**Comment by gianalarcon** [comment]
All yours @SoarinSkySagar .  Please test your implementation thoroughly before submitting it for review. We expect your draft PR within the next 24 hours.
Note: This is a **NON-REWARDED**  issue. Please refer to the OD platform/team for more details.

**Comment by gianalarcon** [comment]
@SoarinSkySagar remember to reate your own branch based on `develop` branch and send your PR to `develop` branch  as well.

**Comment by SoarinSkySagar** [comment]
> All yours @SoarinSkySagar . Please test your implementation thoroughly before submitting it for review. We expect your draft PR within the next 24 hours. Note: This is a **NON-REWARDED** issue. Please refer to the OD platform/team for more details.

gm @gianalarcon, can you please provide your tg username, I think I need more time to create a draft PR. Would be nice to have a little chat over tg!

**Comment by gianalarcon** [comment]
welcome to join our discord https://discord.gg/SC5Am6UG
There is channel for cairo,we can chat there 

> > All yours @SoarinSkySagar . Please test your implementation thoroughly before submitting it for review. We expect your draft PR within the next 24 hours. Note: This is a **NON-REWARDED** issue. Please refer to the OD platform/team for more details.
> 
> gm @gianalarcon, thanks for assigning. can you please provide your tg username, I think I need more time to create a draft PR. Would be nice to have a little chat over tg!

**Comment by gianalarcon** [comment]
@SoarinSkySagar I improved the issue description. Any questions reach me on discord

**Comment by gianalarcon** [comment]
Thanks for joining @SoarinSkySagar . It has been 4 days since the issue got assigned but there is not progress on your side, we will give the chance to another participant.

**Comment by gianalarcon** [comment]
Hi applicants! If someone want to try this issue, please react to this comment

**Comment by SoarinSkySagar** [comment]
> Thanks for joining @SoarinSkySagar . It has been 4 days since the issue got assigned but there is not progress on your side, we will give the chance to another participant.

Really sorry for that, I haven't had the chance to work on it yet. But if it was still assigned I could've surely done it by the end of odhack. but thanks for the opportunity, and sorry that i didn't work on it

**Comment by ncoquelet** [comment]
Can I try solving this issue?
I'll find the best way to use env to configure fork url and look what can be optimise into fork tests

**Comment by gianalarcon** [comment]
closed with #105
