### ISSUE TITLE
Improve current CI/CD

### ISSUE THREAD

**Issue by gianalarcon** [The-Marquis-Gaming/themarquis-ui#90]
## Issue Overview

Add Missing like run test, and more

## Proposed Solutions or Ideas

Outline your proposed solution or share any ideas you have for discussing or resolving the issue.

**Comment by Supa-mega** [comment]
I'd love to work on this!

**Comment by ncoquelet** [comment]
Hey,

I'm a dev with 20 years of XP, super comfy with TypeScript, React/Next, Dapps, Prisma, CI/CD. I ship fast and high-quality stuff. Worked with AFK and GoStarkMe, check my GitHub profile for more details (got several hackathon prizes).
Currently doing Basecamp 11.

Can I try solving this issue?

**Comment by joanne-cmd** [comment]
hello, my name is joanne  and i would love to work on this issues , i have a background in DevSecops, and to improve your cicd pipeline and any missng features

**Comment by BrunoAmbricca** [comment]
I would like to work on this issue

**Comment by Benjtalkshow** [comment]
I am a Full Stack Developer with a strong background in blockchain and extensive experience in Next.js/React, TypeScript, and Rust. I’ve made over 49 contributions to over 17 projects in the OnlyDust ecosystem, solving complex issues and delivering efficient, scalable solutions.

I can handle this task.
ETA is 3days.

**Comment by gianalarcon** [comment]
All yours @joanne-cmd .  Please test your implementation thoroughly before submitting it for review. We expect your draft PR within the next 24 hours.
Note: This is an **NON-REWARDED**  issue. Please refer to the OD platform/team for more details.

**Comment by joanne-cmd** [comment]
@gianalarcon thank you for the opportunity, kindly update the  discord link it is not accessible

**Comment by gianalarcon** [comment]
Please join here, thanks! https://discord.gg/SC5Am6UG

**Comment by gianalarcon** [comment]
All yours @ncoquelet  . Please test your implementation thoroughly before submitting it for review. We expect your draft PR within the next 24 hours. Please join to our [discord](https://discord.gg/SC5Am6UG) here, thanks! 
Note: This is a NON-REWARDED issue. Please refer to the OD platform/team for more details.
