### ISSUE TITLE
Fix minor issues on UI

### ISSUE THREAD

**Issue by Buuh2511** [The-Marquis-Gaming/themarquis-ui#96]
## Issue Overview

- Fix alignment between error message and icon for every device on Login/Signup Page
- Fix alignment between active slide and another one, need to fix width, height, border-radius (Mobile)
- Color and text need to fix on LeaderBoard section
- Fix component "Invitation" match with Figma, also need to cover after login/signup page (PC, Table, Mobile)]
    - /signup/welcome
    - /login/welcome

## Proposed Solutions or Ideas
Pay attention to even the smallest details based on [Figma](https://www.figma.com/design/GtsLINYwGOPcwYcz6nTXXa/The-Marquis-LP---OnlyDust?node-id=0-1&node-type=canvas&t=i7Kp9hywq6eBKAso-0)

**Comment by sonkeydotcom** [comment]
Hi, can i take this

**Comment by GoSTEAN** [comment]
Could I be assigned to this?

**Comment by josephchimebuka** [comment]
Can I take this issue?

**Comment by Supa-mega** [comment]
Could I be assigned to this?

**Comment by zintarh** [comment]
I'd be happy to do this.

**Comment by ncoquelet** [comment]
Hey,

I'm a dev with 20 years of XP, super comfy with TypeScript, React/Next, Dapps, Prisma, CI/CD. I ship fast and high-quality stuff. Worked with AFK and GoStarkMe, check my GitHub profile for more details (got several hackathon prizes).
Currently doing Basecamp 11.

Can I handle this task?

**Comment by obacollins-lab** [comment]
I'd love to take on this issue. can I be assigned?

**Comment by Judah04** [comment]
@Buuh2511, I'd love to work on this.

**Comment by SimplementeCao** [comment]
### Hey! I'm *SimplementeCao*. 👋

I have contributed before to other projects like:

- `Cairo Book`
- `Starknet Book`
- `Starknet Docs`
- `Starknet Security Challenges Factory`
- `Starkane`

Can I work on this issue?

Check my OnlyDust, I've contributed to many projects: [OnlyDust Profile](https://app.onlydust.com/u/SimplementeCao), 
and my [GitHub](https://github.com/SimplementeCao)

---

### Plan to Solve the Issue:

1. **Analyze the codebase** to understand the current structure and functionality.
2. **Review the problem description** that needs to be solved by thoroughly reading the issue details.
3. **Leverage all provided resources** within the issue to get a better grasp of the task at hand.
4. If I face any challenge, I will **ask questions promptly** in the relevant support group or communication channel to move forward efficiently.
5. Once resolved, I will **open a PR** and wait for your feedback.

---

Let me know if I can start working on this! 🚀

---

**Comment by Belloabraham121** [comment]
Hey! I'm Iteooluwakisi.
Member of Web3bridge. I have contributed before to other projects like:
• CoinSafe 
• Scaffold-ETH
• BuidlGuidl
Can I work on this issue?
Plan to Solve the Issue:
Study the codebase to understand the current structure and functionality.
Understand the problem that needs to be solved by thoroughly reading the issue details.
Leverage all provided resources within the issue to get a better grasp of the task at hand.
If I encounter roadblocks, I will ask questions ASAP in the relevant group/chat to move forward effectively.
I will open a PR and wait for your feedback.

**Comment by Belloabraham121** [comment]
Hey! I'm Iteooluwakisi.
Member of Web3bridge. I have contributed before to other projects like:
• CoinSafe 
• Scaffold-ETH
• BuidlGuidl
Can I work on this issue?
Plan to Solve the Issue:
Study the codebase to understand the current structure and functionality.
Understand the problem that needs to be solved by thoroughly reading the issue details.
Leverage all provided resources within the issue to get a better grasp of the task at hand.
If I encounter roadblocks, I will ask questions ASAP in the relevant group/chat to move forward effectively.
I will open a PR and wait for your feedback.

**Comment by kcmikee** [comment]
Hi, I'm Michael Esenwa, a proud alumni of web3bridge I worked with React, TypeScript, including frontend interaction with smart contracts. I'm passionate about design and frontend development and excited to contribute to this project.
 I value clear communication and constructive feedback, as I believe they are key to collaborative success. Happy to contribute!

**Comment by caxtonacollins** [comment]
I will love to start working on this. Please assign me.

**Comment by martinvibes** [comment]
i'm a frontend dev and blockchain dev 
i would love to work on this and get it done
I’m interested in this one.
kindly assign

**Comment by wheval** [comment]
Hello @Buuh2511, Is it okay if I tackle this?
I'm Wheval an experienced frontend developer.
I would ensure to fix all the UI bugs according to the Figma design. 

ETA is 1 day.

**Comment by Jagadeeshftw** [comment]
Hi,
I’d love to work on this issue as I have strong experience with front-end development. Please assign this to me, and I’ll deliver an efficient and secure PR within 12-24 hours.

**Comment by jahrulezfrancis** [comment]
I’ve noted the issues you mentioned, and here’s how I’ll address them. I’ll fix the alignment between the error message and the icon on the Login/Signup page to ensure it looks consistent across all devices. I’ll also adjust the alignment between the active slide and the others on mobile, making sure the width, height, and border-radius are correct. For the LeaderBoard section, I’ll refine the color and text. As for the "Invitation" component, I’ll ensure it matches the Figma design and looks good after the login/signup process, across PC, tablet, and mobile.

I’ll pay close attention to even the smallest details based on the Figma designs to ensure everything is consistent. I can have this wrapped up for you within 24 hours.

**Comment by Storyofmujahid** [comment]
I have a keen eye for details, check my works here: https://dribbble.com/Mujaaahiid.
May I go ahead in solving this issue?

**Comment by zleypner** [comment]
Hi! I’m Anwar a Software Developer with +3 years of experience, and I would love 
make a contribution to this project and contribute to the project's success.

I will fix the alignment between the error message and icon on the Login/Signup page, ensuring it is consistent across all devices. I will also adjust the width, height, and border-radius to properly align the active slide with the others on mobile.

**Comment by BrunoAmbricca** [comment]
I would like to work on this issue

**Comment by ShantelPeters** [comment]
Could I be assigned to this?

**Comment by therealemino** [comment]
Hi, I've over 4 years professional experience working on frontend applications (React, Vue, Next, Nuxt, TS). I've gone through the repository and Figma design. I believe this is an excellent first issue for me to contribute to. Can take on this task?

**Comment by Benjtalkshow** [comment]
I am a Full Stack Developer with a strong background in blockchain and extensive experience in Next.js/React, TypeScript, and Rust. I’ve made over 49 contributions to over 17 projects in the OnlyDust ecosystem, solving complex issues and delivering efficient, scalable solutions.

I can handle this task.
ETA is 3days.

**Comment by Amarjeet325** [comment]
Can I take this issue?

**Comment by vestor-dev** [comment]
hey sir i would love to work on this issue 
i'm a blockchain dev and i would love to handle this issue 
assign me and i'll get to work

**Comment by tosinmoses384** [comment]
Can I take this issue?

**Comment by DuendexCR** [comment]
I'd love to give this a go.

**Comment by davedumto** [comment]
Hi. I'm David, a new open-source contributor, proficient in TypeScript, JavaScript, Tailwind CSS, and ShadCN. I can help fix UI issues by:

Aligning error messages and icons consistently across devices on the Login/Signup pages.
Fixing alignment, width, height, and border-radius for active slides (Mobile).
Correcting color and text styling in the LeaderBoard section.
Ensuring the Invitation component matches Figma designs and is responsive across devices (PC, Tablet, Mobile) on /signup/welcome and /login/welcome.
ETA 3 days

**Comment by Prosper1218** [comment]
let me fix this for you. i'll create my first PR in 50hrs.

I'm prosper Williams a frontend/Blockchain developer, Proefficient in Nextjs{typescript} and tailwind css. Paying attention to design details is a ritual for me, Let me handle this for you.
thanks!

**Comment by caxtonacollins** [comment]
I am a Full Stack Developer with two years of professional experience, specializing in web3. I have strong background in blockchain and extensive experience in Next.js/React, TypeScript, Cairo and Rust.

I will like to take care of this.

**Comment by Favvie** [comment]
Request to Work on Alignment and UI Refinements

Hello, team!

I would like to take on the task of implementing the detailed UI refinements as outlined in the issue. I'll ensure the following steps are carried out precisely:

Plan of Action:
1. Login/Signup Page Refinements:
   - Carefully align error messages with their corresponding icons across all device types

2. Mobile Slide Alignment:
   - Adjust styles based on the figma file of active and adjacent slides
   - Ensure smooth and consistent visual transition between slides

3. LeaderBoard Section Updates:
   - Correct color schemes as per the original design
   - Adjust text formatting and alignment as specified in the figma file
   

4. Invitation Component Implementation:
   - Ensure pixel-perfect implementation of the Invitation component to match with Figma design 
   - Ensure pixel-perfect implementation for:
     * /signup/welcome page
     * /login/welcome page
   - Verify responsiveness across PC, Tablet, and Mobile devices

Approach:
- Pixel-level attention to design details
- Cross-device compatibility testing
- Precise implementation following Figma specifications

I commit to delivering a high-quality implementation that meets all the specified requirements. I'll ensure careful attention to even the smallest design details.

Thank you for the opportunity to work on this task!

ETA: 48 - 72 Hours

**Comment by gianalarcon** [comment]
All yours @therealemino.  Please test your implementation thoroughly before submitting it for review. We expect your draft PR within the next 24 hours. 
Create your onw branch based on `develop` branch and send your PR to `develop` branch  as well.

**Comment by therealemino** [comment]
Thanks a lot @gianalarcon. Will get to it ASAP 🚀

**Comment by therealemino** [comment]
Hi @gianalarcon, I've tried joining the discord community a couple of times and the link is expired (https://discord.com/invite/8A59FkYD).
I need to reach out to the admins privately to request some of the ENVs.

**Comment by gianalarcon** [comment]
Please join here
https://discord.gg/SC5Am6UG

**Comment by gianalarcon** [comment]
closed with #98
